name: test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        rustup toolchain install stable --profile minimal --component clippy
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run:
        cargo test
